version: "3"

volumes:
  WW2021Data:

services:
  main:
    image: wind-with-2021:1.5.0
    build: .
    ports:
      - "8603:8603"
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
      - "./banned.yaml:/app/banned.yaml:ro"
      - "WW2021Data:/data"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 384M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1s
